from .library import Library as Library

VAL_SEP: str
PARSING_FAILED_COMMENT: str

def write(library: Library, bibtex_format: BibtexFormat | None = None) -> str: ...

class BibtexFormat:
    def __init__(self) -> None: ...
    @property
    def indent(self) -> str: ...
    @indent.setter
    def indent(self, indent: str) -> None: ...
    @property
    def value_column(self) -> int | str: ...
    @value_column.setter
    def value_column(self, align_values: int | str) -> None: ...
    @property
    def block_separator(self) -> str: ...
    @block_separator.setter
    def block_separator(self, entry_separator: str) -> None: ...
    @property
    def trailing_comma(self) -> bool: ...
    @trailing_comma.setter
    def trailing_comma(self, trailing_comma: bool) -> None: ...
    @property
    def parsing_failed_comment(self) -> str: ...
    @parsing_failed_comment.setter
    def parsing_failed_comment(self, parsing_failed_comment: str) -> None: ...
